In [1]:
import math

%load_ext autoreload
%autoreload 2
from benchmark_tool import run_benchmark, run_benchmark_as_subprocess

In [2]:



def cpu_task(n):
    """A CPU-Bound task--no real memory usage, no waiting."""
    x = 0
    for i in range(n):
        x += math.sqrt(i * 10 + 5.2)

run_benchmark(cpu_task, n_repeats=100, task_params={'n': 10000})

{'run_id': 'ec9c1460',
 'wall': 0.1537,
 'process': 0.1562,
 'cpu_percent': 100.2,
 'io_read_count': 1,
 'io_read_bytes': 0,
 'io_read_rate': 0.0,
 'io_write_count': 11,
 'io_write_bytes': 24608,
 'io_write_rate': 160087.954684}

In [3]:
%%writefile task.py

import math

def cpu_task(n):
    """A CPU-Bound task--no real memory usage, no waiting."""
    x = 0
    for i in range(n):
        x += math.sqrt(i * 10 + 5.2)

Overwriting task.py

In [7]:
run_benchmark_as_subprocess('task:cpu_task', params=dict(n=5))

{'run_id': 'ddd8bade',
 'wall': 0.0,
 'process': 0.0,
 'cpu_percent': 0.0,
 'io_read_count': 0,
 'io_read_bytes': 0,
 'io_read_rate': 0.0,
 'io_write_count': 0,
 'io_write_bytes': 0,
 'io_write_rate': 0.0}

In [21]:
import time
import pandas as pd

def io_task(n):
    """An IO-Bound task--just waiting."""
    for i in range(n):
        time.sleep(0.000001)

pd.DataFrame([run_benchmark(io_task, dict(n=50)) for _ in range(10)])

,run_id,wall,process,cpu_percent,io_read_count,io_read_bytes,io_read_rate,io_write_count,io_write_bytes,io_write_rate
0,5e96c2a4,0.0296,0.0000,0.0,1,0,0.0,11,24608,831820.655623
1,2cd7adeb,0.0293,0.0156,48.8,0,0,0.0,0,0,0.000000
2,4ad89a3f,0.0293,0.0000,0.0,0,0,0.0,0,0,0.000000
3,ac8bedd6,0.0296,0.0000,0.0,0,0,0.0,0,0,0.000000
4,75def970,0.0298,0.0000,0.0,0,0,0.0,0,0,0.000000
5,b9544c9f,0.0290,0.0000,0.0,0,0,0.0,0,0,0.000000
6,a029bcbb,0.0298,0.0000,0.0,0,0,0.0,0,0,0.000000
7,ea4ca0a6,0.0296,0.0000,0.0,0,0,0.0,0,0,0.000000
8,abe516d4,0.0296,0.0000,0.0,0,0,0.0,0,0,0.000000
9,a68045b7,0.0294,0.0000,0.0,0,0,0.0,0,0,0.000000

In [32]:
import time
import pandas as pd

def io_task(n):
    """An IO-Bound task--just waiting."""
    with open('mydata.txt', 'wb') as f:
        f.write(b"i" * 100)

pd.DataFrame([run_benchmark(io_task, dict(n=50), n_repeats=1000) for _ in range(10)])

,run_id,wall,process,cpu_percent,io_read_count,io_read_bytes,io_read_rate,io_write_count,io_write_bytes,io_write_rate
0,9a740bf9,0.1628,0.1562,110.8,1,0,0.0,1011,124608,765501.798400
1,50d3232c,0.1690,0.1562,83.6,0,0,0.0,1000,100000,591542.013995
2,b01a0aa1,0.1622,0.1562,99.5,0,0,0.0,1000,100000,616385.625679
3,737b0169,0.1566,0.1562,90.8,0,0,0.0,1000,100000,638606.305632
4,a95d87aa,0.1625,0.1562,111.6,0,0,0.0,1000,100000,615408.474292
5,1159632e,0.1596,0.1562,90.8,0,0,0.0,1000,100000,626480.059171
6,9464f6e0,0.1672,0.1719,110.2,0,0,0.0,1000,100000,598184.867821
7,454973dc,0.1563,0.1406,89.6,0,0,0.0,1000,100000,639616.434815
8,8f53b5dd,0.1587,0.1562,91.4,0,0,0.0,1000,100000,629924.434222
9,08942ef5,0.1858,0.1562,83.1,0,0,0.0,1000,100000,538235.148500

In [33]:
0.1719 / 0.1672

1.02811004784689

In [ ]:

def numpy_task(n):
    """A CPU-Bound task done out-of-Python."""
    start_cpu = time.process_time()
    a = np.random.rand(n, n)
    b = np.random.rand(n, n)
    np.matmul(a, b)
    return time.process_time() - start_cpu

Signature:
run_benchmark(
    task: Callable,
    batch_executor: benchmark_tool.Executor,
    *args,
    **kwargs,
) -> dict[str, 'JSON']
Docstring: Runs code and measures elapsed time.
File:      c:\users\delgr\projects\hhai-repo\notebooks\04_profiling\benchmark_tool.py
Type:      function